config/routes.rb
Rails.application.routes.draw do
  root to: 'customers#index'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :customers, except: [:delete]
  resources :customer do
    resources :kaltes, except: [:index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  enum gender:
  {
    man: 0,
    woman: 1
  }
   validates :name, presence: true, length: { maximum: 50 }

   VALID_BERTHDAY_REGEX = /\A\d{4}-\d{2}-\d{2}\z/
   validates :birthday, presence: true, length: { maximum: 20},
                        format: { with: VALID_BERTHDAY_REGEX }

   validates :address, presence: true, length: { maximum: 50 }

   VALID_PHONE_REGEX = /\A\d{10,11}\z/
   validates :phone, presence: true, length: { maximum: 15 },
                    format: { with: VALID_PHONE_REGEX = /\A\d{10,11}\z/ }

   validates :gender, presence: true
   
   has_many :kaltes

   scope :recent, -> { order(created_at: :desc) }

  def self.ransackable_attributes(auth_object = nil)
    %w[name phone]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/kalte.rb
class Kalte < ApplicationRecord
  validates :menu, presence: true, length: { maximum: 50 }
  validates :request, presence: true, length: { maximum: 500 }
  validates :menu_description, presence: true, length: { maximum: 500 }
  validates :note, presence: true, length: { maximum: 500 }

  belongs_to :customer
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_save :downcase_email
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_PHONE_REGEX = /\A\d{10,11}\z/
  validates :phone, presence: true, format: { with: VALID_PHONE_REGEX }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
              format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  scope :recent, -> { order(created_at: :desc) }

  def self.ransackable_attributes(auth_object = nil)
    %w[name phone]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  private
    def downcase_email
      email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private
    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def login_required
      redirect_to login_url unless current_user
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
before_action :set_customer, only: [:show, :edit, :update]

  def index
    customers = Customer.all
    # gem'ransack'で検索可能にしている
    @q = customers.ransack(params[:q])
    @customers = @q.result(distinct: true).page(params[:page]).per(15)
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to @customer, flash: { success: "「#{@customer.name}様」を登録しました" }
    else
      render :new
    end
  end

  def show
    @kaltes = @customer.kaltes
  end

  def edit
  end
  
  def update
    if @customer.update(customer_params)
    redirect_to @customer, flash: { success: "顧客情報を更新しました" }
    else
      render :edit
    end
  end

 private
   def customer_params
    params.require(:customer).permit(:name, :birthday, :address, :phone, :gender)
   end

   def set_customer
    @customer = Customer.find(params[:id])
   end
end

app/controllers/kaltes_controller.rb
class KaltesController < ApplicationController
  before_action :current_customer
  before_action :set_kalte, only: [:show, :edit, :update, :destroy]

  def new
    @kalte = Kalte.new
  end
  
  def show
  end
  
  def create
    @kalte = Kalte.new(kalte_params)
    if @kalte.save
      redirect_to customer_kalte_path(@kalte.customer_id, @kalte.id), flash: { success: 'カルテを作成しました' }
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @kalte.update(kalte_params)
      redirect_to customer_kalte_path(@kalte.customer_id, @kalte.id), flash: { success: 'カルテを更新しました' }
    else
      render :edit
    end
  end

  def destroy
    @kalte.destroy
    redirect_to customer_path(@kalte.customer_id), flash: { success: "カルテを削除しました" }
  end

  private
    def kalte_params 
      params.require(:kalte).permit(:menu, :request, :menu_description, :note, :image).merge(customer_id: params[:customer_id])
    end

    def current_customer
      @customer = Customer.find(params[:customer_id])
    end

    def set_kalte
      @kalte = Kalte.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, flash: { success: "ログインしました" }
    else
      flash.now[:danger] = 'Eメールまたはパスワードが正しくありません'
      render :new
    end
  end

  def destroy 
    reset_session
    redirect_to login_path, flash: { success: "ログアウトしました" }
  end

  private
    def session_params
      params.require(:session).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: :show
  def index
    users = User.all
    @q = users.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(15)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) 
    if @user.save
      redirect_to @user, flash: { success: "スタッフ#{@user.name}を登録しました" }
    else
      render :new    
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, flash: { success: "#スタッフ情報を更新しました" }
    else
      render :edit
    end
  end

  def show
  end

  def destroy 
    @user.destroy
    redirect_to users_path, flash: { success: "#{@user.name}を削除しました" }
  end

  private
    def user_params
      params.require(:user).permit(:name, :phone, :email, :password, :password_confirmation)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_admin
      redirect_to root_url unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/kaltes_helper.rb
module KaltesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/_form.html.slim
/ 検証エラーのメッセージかあれば表示する
- if @customer.errors.present?
 ul#error_explanation 
  - @customer.errors.full_messages.each do |message|
    li.alert.alert-danger role="alert" = message

= form_with model: customer, local: true do |f|
  .form-group
    = f.label :name, class: 'form-label'
    = f.text_field :name, id: 'customer_name', class: 'form-control form-control-lg form'
  .form-group
    = f.label :birthday, class: 'form-label'
    = f.date_field (:birthday) , class: 'form-control form-control-lg form'
  .form-group
    = f.label :address, class: 'form-label'
    = f.text_field :address, id: 'customer_address', class: 'form-control form-control-lg form'
  .form-group
    = f.label :phone, class: 'form-label'
    = f.text_field :phone, id: 'customer_phone', class: 'form-control form-control-lg form'
  .row
    .col-3.col-md-2.col-lg-1
      .form-check
        = f.radio_button :gender, :man, class: 'form-check-input'
        = f.label :gender, "男性", { value: :man } 
    .col-3.col-md-2.col-lg-1
      .form-check
        = f.radio_button :gender, :woman, class: 'form-check-input'
        = f.label :gender, "女性", { value: :woman }
  .float-end
    = f.submit nil, class: 'btn btn-lg btn-outline-primary'

app/views/customers/edit.html.slim
h1.page-title 顧客情報編集

= render partial: 'form', locals: { customer: @customer }

= link_to '顧客情報詳細', @customer

app/views/customers/index.html.slim
#customer-index
  h1.page-title 顧客一覧
  .float-end 
    = link_to "顧客登録", new_customer_path, class: "link"

  / 検索フォーム
  = search_form_for @q, class: 'md-5' do |f|
    .row
      .col-md-5
        .form-group
          = f.label :name_cont, '氏名', class: 'col-sm-2 col-form-label'
          = f.search_field :name_cont, class: 'form-control'
      .col-md-5 
        .form-group
          = f.label :phone_cont, '電話番号', class: 'col-sm-4 col-form-label'
          = f.search_field :phone_cont, class: 'form-control'
      .col-md-2 
        .form-group 
          = f.submit class: 'btn btn-outline-primary '

  .md-3
    = paginate @customers, theme: 'bootstrap-5'

  table.table.table-striped.table-hover
    thead.table-dark
      tr 
        th scope='col' = Customer.human_attribute_name(:id)
        th scope="col" = Customer.human_attribute_name(:name)
        th scope='col' =  Customer.human_attribute_name(:phone)
    tbody 
      - @customers.each do |customer|
        tr
          td= customer.id 
          td= link_to customer.name, customer
          td= customer.phone

  = paginate @customers, theme: 'bootstrap-5'

app/views/customers/new.html.slim
h1.page-title 顧客登録

.float-end
  = link_to '顧客一覧', customers_path, class: "link"

= render partial: 'form', locals: { customer: @customer }

app/views/customers/show.html.slim
#customer_show
  h1.page-title 顧客詳細
  .float-end
    = link_to '顧客一覧', customers_path

  table.table
    tr 
      th scope='col' = Customer.human_attribute_name(:id) 
      td = @customer.id
    tr
      th scope='col' = Customer.human_attribute_name(:name)
      td = @customer.name
    tr 
      th scope='col' = Customer.human_attribute_name(:phone)
      td = @customer.phone
    tr
      th scope='col' = Customer.human_attribute_name(:birthday)
      td = @customer.birthday.strftime('%Y/%m/%d')
    tr 
      th scope='col' = Customer.human_attribute_name(:gender)
      td = @customer.gender_i18n

  = link_to '編集',  edit_customer_path, class: 'btn btn-primary'
  = link_to 'カルテ作成', new_customer_kalte_path(@customer), class: 'btn btn-primary'

  table.table 
    thead
      tr 
        th scope='col' = Kalte.human_attribute_name(:created_at)
        th scope='col' = Kalte.human_attribute_name(:menu)
    tbody 
      - @kaltes.each do |kalte|
        tr
          td = kalte.created_at.strftime('%Y/%m/%d')
          td = link_to kalte.menu, customer_kalte_path(kalte.customer_id, kalte.id)
          td 
            = link_to '編集', edit_customer_kalte_path(kalte.customer_id, kalte.id), class: 'btn btn-primary'
            = link_to '削除', customer_kalte_path(kalte.customer.id, kalte.id), method: :delete, data: { confirm: "カルテを削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/kaltes/_form.html.slim
#kalte-form
  - if kalte.errors.present?
  ul#error_explanation 
    - kalte.errors.full_messages.each do |message|
      li.alert.alert-danger role="alert" = message

  = form_with model: [customer,kalte], local: true do |f|
    .form-grop
      = f.label :menu, class: 'form-label'
      = f.text_field :menu, class: 'form-control form-control-lg form'
    .row
      .col-md-8
        .form-grop
          = f.label :request, class: 'form-label'
          = f.text_area :request , class: 'form-control kalte-form form'
      .col-md-4
        .form-group
          = f.label :image, class: "form-label"
          = f.file_field :image, class: 'form-control form-control-lg form'
    .form-group
      = f.label :menu_description, class: 'form-label'
      = f.text_area :menu_description, class: 'form-control kalte-form form'
    .form-group
      = f.label :note, class: 'form-label'
      = f.text_area :note, class: 'form-control kalte-form form'
    .float-end
      = f.submit nil, class: 'btn btn-outline-primary'

app/views/kaltes/edit.html.slim
h1.page-title カルテ情報編集

= render partial: 'form', locals: { customer: @customer, kalte: @kalte }

app/views/kaltes/new.html.slim
h1.page-title カルテ作成

= render partial: 'form', locals: { customer: @customer, kalte: @kalte } 

app/views/kaltes/show.html.slim
#kalte-show
  h1.page-title カルテ詳細

  .row
    .col-md-5
      table.table.kalte-table
        tr 
          th scope='col' = Kalte.human_attribute_name(:created_at) 
          td = @kalte.created_at.strftime('%Y/%m/%d')
    .col-md-5
      table.table.kalte-table
        tr
          th scope='col' = Kalte.human_attribute_name(:menu) 
          td = @kalte.menu

  .row
    .col-md-8
      table.table.kalte-table
        thead
          tr 
            th scope='col' = Kalte.human_attribute_name(:request)
        tbody 
          tr 
            td = @kalte.request
      table.table.kalte-table
        thead 
          tr 
            th scope='col' = Kalte.human_attribute_name(:menu_description)
        tbody 
          tr 
            td = @kalte.menu_description
      table.table.kalte-table
        thead 
          tr 
            th scope='col' = Kalte.human_attribute_name(:note)
        tbody 
          tr 
            td = @kalte.note

    .col-md-4
      table.table.kalte-table
        thead
          tr 
            th scope='col' = Kalte.human_attribute_name(:image)
        tbody 
          tr 
            td = image_tag @kalte.image if @kalte.image.attached? 
  


  .float-end
    = link_to '編集', edit_customer_kalte_path(@kalte), class: 'btn btn-primary'

    = link_to '削除', customer_kalte_path(@kalte.customer.id, @kalte.id), method: :delete, data: { confirm: "カルテを削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ElectronicKalte
    = csrf_meta_tags
    = csp_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1"
    link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"
  body
    header
      nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
        .container-fluid
          = link_to 'Electoronic Kalte', root_path, class: 'navbar-brand'
          button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"
            span.navbar-toggler-icon
          .collapse.navbar-collapse.justify-content-end#navbarNav
            ul.navbar-nav
              - if current_user
                li.nav-item 
                  =link_to current_user.name, user_path(current_user), class: "nav-link"
                li.nav-item
                  =link_to '顧客登録', new_customer_path, class: 'nav-link'
                li.nav-item
                  =link_to '顧客一覧', customers_path, class: 'nav-link'
                - if current_user.admin?
                  li.nav-item
                    =link_to 'スタッフ一覧', users_path, class: 'nav-link'
                li.nav-item
                  =link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}") 
      = yield

app/views/users/_form.html.slim
- if user.errors.present?
 ul#error_explanation 
  - user.errors.full_messages.each do |message|
    li.alert.alert-danger role="alert" = message

= form_with model: user, local: true do |f|
  .form-group
    = f.label :name, class: 'form-label'
    = f.text_field :name, class: 'form-control form-control-lg form'
  .form-group
    = f.label :phone, class: 'form-label'
    = f.text_field :phone , class: 'form-control form-control-lg form'
  .form-group
    = f.label :email, class: 'form-label'
    = f.text_field :email, class: 'form-control form-control-lg form'
  .form-group 
    = f.label :password, class: 'form-label'
    = f.password_field :password, class: 'form-control form-control-lg form'
  .form-group 
    = f.label :password_confirmation, class: 'form-label'
    = f.password_field :password_confirmation, class: 'form-control form-control-lg form'
  .float-end
    = f.submit nil, class: 'btn btn-outline-primary'

app/views/users/edit.html.slim
h1.page-title スタッフ情報編集
.float-end
  = link_to "スタッフ一覧", users_path, class: "link" 

= render partial: "form", locals: { user: @user }

app/views/users/index.html.slim
#users-index
  h1.page-title スタッフ一覧

  .float-end
    = link_to '新規登録',  new_user_path, class: "link"

  / 検索フォーム
  = search_form_for @q, class: 'md-5' do |f|
    .row
      .col-md-5
        .form-group
          = f.label :name_cont, '氏名', class: 'col-sm-2 col-form-label'
          = f.search_field :name_cont, class: 'form-control'
      .col-md-5
        .form-group.
          = f.label :phone_cont, '電話番号', class: 'col-sm-4 col-form-label'
          = f.search_field :phone_cont, class: 'form-control'
      .col-md-2
        .form-group 
          = f.submit class: 'btn btn-outline-primary'


  .md-3
    = paginate @users, theme: 'bootstrap-5'

  table.table.table-striped.table-hover
    thead.table-dark
      tr 
        th = User.human_attribute_name(:name)
        th = User.human_attribute_name(:phone)
        th = User.human_attribute_name(:created_at)
    tbody 
      - @users.each do |user|
        tr 
          td= link_to user.name, user
          td= user.phone
          td= user.created_at.strftime('%Y/%m/%d')

  = paginate @users, theme: 'bootstrap-5'
        
         

app/views/users/new.html.slim
h1.page-title スタッフ登録

= render partial: "form", locals: { user: @user }

app/views/users/show.html.slim
#users-show
  h1.page-title スタッフ詳細

  .float-end
    - if current_user.admin?
      == link_to  "スタッフ一覧", users_path, class: "link"

  table.table
    tr 
      th scope="col" = User.human_attribute_name(:name)
      td = @user.name
    tr 
      th scope="col" = User.human_attribute_name(:phone)
      td = @user.phone 
    tr 
      th scope="col" = User.human_attribute_name(:email)
      td = @user.email 

    tr  
      th scope="col" = User.human_attribute_name(:admin)
      td = @user.admin? ? 'あり' : 'なし'
    tr 
      th scope="col" = User.human_attribute_name(:created_at)
      td = @user.created_at.strftime('%Y/%m/%d')
    tr 
      th scope="col" = User.human_attribute_name(:updated_at)
      td = @user.updated_at.strftime('%Y/%m/%d')
    
  =link_to "顧客一覧", customers_path, class: "link"
  
  .float-end
    = link_to "編集", edit_user_path(@user), class: "btn btn-primary"

    = link_to "削除", user_path(@user), method: :delete, data: { confirm: "#{@user.name}を削除します。よろしいですか？" }, class: 'btn btn-danger'

    - if @user == current_user
      = link_to "ログアウト", logout_path, method: :delete, class: "btn btn-secondary"